In [1]:
import numpy as np

In [2]:
a = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [3]:
a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
a.size

9

In [5]:
a.ndim

2

In [6]:
a.shape

(3, 3)

In [7]:
a[0][0]  # Access different elements of the array
         # first: row, second: column

11

In [10]:
a[0,0]  # another way

11

In [11]:
a[0,0:2]

array([11, 12])

In [12]:
x = np.array([[2,1],[1,2]])
y = np.array([[0,1],[3,2]])

In [14]:
x + y

array([[2, 2],
       [4, 4]])

In [15]:
x * y  # multiply elements in the same location 2*0, 1*1, 1*3, 2*2
       # Hadamard product

array([[0, 1],
       [3, 4]])

In [16]:
x *2

array([[4, 2],
       [2, 4]])

In [17]:
np.dot(x,y)  # Matrix product

array([[3, 4],
       [6, 5]])

In [19]:
y.T # Transpose of y

array([[0, 3],
       [1, 2]])

In [ ]:
# docs.python.org/3/

In [ ]:
# For more information Check out numpy.org